### ISSUE TITLE
Bottom Menu Shifts to Left When Timer is minimized

### ISSUE THREAD

**Issue by saryal** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#75] opened 2019-03-26 19:12 UTC

**Comment by saryal** [comment] 2019-03-26 19:17
![File Mar 26, 12 15 47](https://user-images.githubusercontent.com/26528506/55026843-0d2f5900-4fc1-11e9-9c82-5120fe02fbed.jpeg)

**Comment by saryal** [comment] 2019-03-26 19:19
Device: iPhone X
OS: iOS 12.2.0 (Previous time occurred on a previous build of iOS 12)
App Version 1.10.1

**Comment by JonnyBeeGod** [comment] 2019-05-01 05:54
Duplicate of #70

**Closed by JonnyBeeGod** 2019-05-01 05:54 UTC
