### ISSUE TITLE
Remembering Accessories

### ISSUE THREAD

**Issue by tristanfcraig** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#49] opened 2018-05-24 16:39 UTC
It would be awesome if, similar to the main lifts, the app would remember which accessories were used on a per-workout basis and increment them additionally on a per-workout basis.

**Comment by amIevenAcoder** [comment] 2018-07-13 18:55
This would be the best thing to add now imo. Save accessories and increment every week or when you hit all reps.

**Comment by jo3p** [comment] 2018-07-13 22:22
Not sure if I can “vote” for this as well, but if it’s not too hard to code I’d like to request the same thing ❤️❤️

**Comment by JonnyBeeGod** [comment] 2018-10-05 06:14
Closed because it's a duplicate of #54. Automatic incrementing of accessories will most likely not be implemented since there is no common denominator on when and how to progress on the accessories. It is so individual that there is no point in automating it

**Closed by JonnyBeeGod** 2018-10-05 06:14 UTC
Labels: Accessories
