### ISSUE TITLE
Timer breaks when exercise marked finished before timer ends

### ISSUE THREAD

**Issue by dimaulupov** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#89] opened 2019-11-18 22:04 UTC
**Did you look whether there is already an existing issue for your request?**
Yes. 

**Describe the bug**
Finishing exercise before timer finishes breaks the timer. 

**To Reproduce**

Finish exercise. 
Timer starts. 
Finish next exercise before timer runs out. 
Timer restarts (it will finish too early, looks like at finish time of the first timer, but don't let it finish too see next error). 
Finish another exercise before timer. 
(After 3-4 iteration timer does not appear at all, but background notifications still popup)

**Expected behavior**
Normal timer starts/stops. 

**Screenshots**
I can make a video. Screenshot will be just without timer. 

**Smartphone (please complete the following information):**
 - Devices: iPhone 8, iPhone 11. 
- iOS: 13.0.1, 13.2.2

**Additional context**
I think it was broken for a while. I just thought someone else will report it.

**Comment by JonnyBeeGod** [comment] 2019-12-29 13:51
Hey, thx for reporting. I did some major rework around the timer, looks like it is fixed at least I can not reproduce it anymore. Will submit a new version to Apple review soon

**Comment by JonnyBeeGod** [comment] 2019-12-31 04:27
Fixed in 1.13.2. Please reopen if problem still persists after updating

**Closed as completed by JonnyBeeGod** 2019-12-31 04:27 UTC
Labels: bug
