### ISSUE TITLE
Deloaded to 45

### ISSUE THREAD

**Issue by firedev** [JonnyBeeGod/nSuns-5-3-1-iOS-issues#46] opened 2018-05-05 00:46 UTC
I could not do 8 presses in one cycle, when TM was 120, so I didn’t fill it, nailed it the next week, then 125, and now for the next cycle it suddenly deloaded overhead press to 45 instead of 130.

**Comment by JonnyBeeGod** [comment] 2018-05-07 08:13
Wich template are you using?

**Comment by JonnyBeeGod** [comment] 2018-05-21 05:54
Since the progression has been reworked with 1.7.0 there is a good chance this issue has been fixed. If not, please reopen this issue with information about the used template

**Comment by firedev** [comment] 2018-08-29 02:38
Hi, I am using 6-day squat, increased AMRAP to 3+ and last week I stated a new cycle where I had to deload OHP to 135. I failed on two monday T2 sets, but it increased OHP this week to 140 anyway. I completed all T1 OHP sets with 3+ AMRAP though.

Is it a bug?

**Comment by JonnyBeeGod** [comment] 2018-08-29 05:56
Hi, tough call. The spreadsheet says „How much you will increase your TM each week is based on how you perform in the 1+ set each day“ which led me to implement it as it is right now. 
It also says „Each week, increase your training max if you were able to complete all the reps“ but it does not say whether T2 should be taken into account as well. Its a business question which should be answered by the community.

**Comment by firedev** [comment] 2018-09-05 05:14
Okay there is a nice comment in this thread https://www.reddit.com/r/nSuns/comments/684r2c/question_on_what_to_do_if_you_fail_non_amrap_sets/

> If you're getting 2 or more reps in the 1+ but missing a rep or two elsewhere: It's really up to you. You could take Anon1369's philosophy and deload, or you could press onwards if your 1+ is still going well. It's your body and I've seen both sides make a compelling case. I don't think either is objectively right or wrong, but I'd encourage trying both routes and seeing which works better for your body. You could deload this time but press on next time, or press on and see if you start getting your reps back, and deload if it comes up again.

Guess I would like to progress slowly but surely, but indeed that's up to the user. Maybe there should be a switch? But then what - global or per lift? I can lift pretty pretty heavy on AMRAP OHP day, but fail to complete the T2 lifts on Monday. And just noticed that it keeps increasing.

**Comment by JonnyBeeGod** [comment] 2018-09-07 03:34
The initial discussion was a bug you reported where it deloaded your lift suddenly inexplicably to 45. Without further data to reproduce this issue I can't do much unfortunately so I think I'm gonna close this issue for now. Regarding the comment you made before this one I think what we gonna need is some kind of accessible way to alter progression in edge cases like this, so maybe #36 could help. The discussion whether the app should increase when failing a set on a T2 can be here #62

**Closed by JonnyBeeGod** 2018-09-07 03:34 UTC
